# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{attribute_mapper}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcel Molina Jr.", "Bruce Williams", "Adam Keys"]
  s.date = %q{2010-01-08}
  s.description = %q{Provides a transparent interface for mapping symbolic representations to a column in the database of a more primitive type.}
  s.email = %q{adamkkeys@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION.yml",
     "attribute_mapper.gemspec",
     "init.rb",
     "lib/attribute_mapper.rb",
     "test/attribute_mapper_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/therealadam/attribute_mapper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Map symbolic types to primitive types and stash them in a column.}
  s.test_files = [
    "test/attribute_mapper_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

